# 에러 처리 // 11월 18일 (Thu)

## 에러 처리의 필요성

### 에러가 발생하지 않는 코드를 작성하는 것은 불가능하다. 따라서 에러는 언제나 발생할 수 있다. 빌생한 에러에 대해 대처하지 않고 방치하면 프로그램은 강제 종료된다.

```
console.log("start");
foo(); // ReferenceError: foo is not defined
console.log("end); // 바로 윗줄 코드의 에러에 의해 프로그램이 강제 종료되어 이 코드는 실행되지 않는다.
```

### try, catch문을 사용해 발생한 에러에 적절하게 대응하면 프로그램이 강제 종료되지 않고 계속해서 코드를 실행시킬 수 있다.

```
console.log("start");

try {
  foo();
} catch (err) {
  console.log(err) // ReferenceError: foo is not defined
}
// 발생하는 에러에 적절하게 대응을 하면 프로그램이 강제 종료되지 않는다.
console.log("end");
```

## try, catch, finally 문

### 일반적으로 이 방법을 에러 처리라고 한다. try, catch, finally 문은 3개의 코드 블록으로 구성된다. finally문은 불필요하다면 생략 가능하다. catch문도 생략 가능하지만 catch 문이 없는 try문은 의미가 없으므로 생략하지 않는다.

```
try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
}
```

#### catch 문의 err변수의 이름은 무엇이든 상관없다. err 변수는 catch 코드 블록에서만 유효하다.

## Error 객체

### Error 생성자 함수는 에러 객체를 생성한다. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메세지를 인수로 전달할 수 있다.

```
const error = new Error("invalid");
```

#### 자바스크립트는 Error 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다. (SyntaxError, ReferenceError, TypeError, RangeError, URIError, EvalError) 이 생성자 함수가 생성한 에러 객체의 프로토타입은 모두 Error.prototype을 상속 받는다.

## throw 문

### Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다. 즉, 에러 객체 생성과 에러 발생은 의미가 다르다.

```
try {
  // 에러 객체를 생성한다고 에러가 발생하는 것은 아니다.
  new Error("error");
} catch (err) {
  console.log(err);
}
```

#### 에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 한다.

```
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error("error");
} catch (err) {
  console.log(err);
}
```

## throw된 에러를 캐치하지 않으면 호출자 방향으로 전파된다. 이때 throw된 에러를 캐치하여 적절히 대응하면 프로그램을 강제 종료시키지 않고 코드의 실행 흐름을 복구할 수 있다. throw된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료된다.
